### ISSUE TITLE
Unable to generate if destination directory does not contain go files

### ISSUE THREAD

**Issue by andcan** [hexdigest/gowrap#15]
When trying to generate files with -o option pointing to an empty directory the command fails with
`failed to load destination package <relative_destination_package_path> -: unknown import path <full_destination_package_path>: cannot find module providing package <full_destination_package_path>`

The error goes away if any .go file is created into destination directory.

**Comment by hexdigest** [comment]
@andcan 
Thanks for raising the issue! Please check if v1.1.3 works for you.
