### ISSUE TITLE
log template not emitting anything if method returns value but no error

### ISSUE THREAD

**Issue by sjames-iberis** [hexdigest/gowrap#2]
Very minor point about the provided log template.  
If I have a method that returns a single result, but not an error, the template generates a deferred function to set the results but these are not emitted by a log call.  
Consequently, the generated code fails to compile because of an unused variable.

I addressed the issue by adding the following before line 42 of the template:
```
{{else}}   
  _d._stdlog.Println(_results...)
```

**Comment by hexdigest** [comment]
@sjames-iberis 
Fixed, thanks!

**Comment by sjames-iberis** [comment]
Not raising a new issue, but I also notice that line 46 of the log template is wrong (extra quotation mark):
```
_d._stdlog.Println(""{{$decorator}}: {{$method.Name}} finished")
```

**Comment by hexdigest** [comment]
@sjames-iberis thank you so much! Actually I discovered a bug in fallback template after extending test interface with the method with no params or results.
