### ISSUE TITLE
Imports of modules with custom names are not included into generated code

### ISSUE THREAD

**Issue by kop** [hexdigest/gowrap#21]
The generator does not work with the case when the name of the package imported into source file does not match last import path segment.

For example, source file like

```go
package authz

import (
	"mymodulename/pkg/api/iam/v1" // Go package name is "iamv1"
)

type Enforcer interface {
	Enforce(ctx context.Context, request *iamv1.Request) ([]string, error)
}
```

Will result generated code that is using `*iamv1.Request` type in method signatures, however `mymodulename/pkg/api/iam/v1` will not be added to the imports section.

I tried all sorts of aliases for this module, however, nothing helps. Generator only works if I rename imported package to `v1`.

**Comment by hexdigest** [comment]
@kop can you please try v1.1.10 with {{.Import}} template helper and without it?

**Comment by cheshir** [comment]
@hexdigest I've got error with {{ .Import }}
`template: body:5:5: executing "body" at <.Import>: can't evaluate field Import in type generator.TemplateInputs`

**Comment by cheshir** [comment]
Anyway, it could be great to use common templates without patching it due to the several packages.
In my case I have interface Foo in package "domain.com/proto/service/v1/sub" and package name "service".
Right now gowrap generates me:
```
type FooWithPrometheus struct {
	base         service.Foo
```

and it's the code I want but there is no import.

**Comment by hexdigest** [comment]
Hi @cheshir ! Thanks for testing this. I think you're gowrap binary is not up to date. 
The error you're getting basically says that there's no Import method. 
Can you please update gowrap and try again?

**Comment by hexdigest** [comment]
> Anyway, it could be great to use common templates without patching it due to the several packages.

I agree with this we have to update common templates and use this new {{.Import}} helper everywhere.

**Comment by hexdigest** [comment]
> But I can't prove it
```bash
$ md5sum `which gowrap`

$ curl https://github.com/hexdigest/gowrap/releases/download/v1.1.10/gowrap_1.1.10_Linux_x86_64.tar.gz -L -o /tmp/gowrap.tar.gz && cd /tmp/ && tar zxvf gowrap.tar.gz && md5sum /tmp/gowrap
```

If hashes are different then you use outdated version (correct the above curl for your platform)

**Comment by cheshir** [comment]
Hm, you were perfectly right. I had the wrong version. With the v1.1.10 everything works well with the Import directive.
