### ISSUE TITLE
comments on the top of generated file

### ISSUE THREAD

**Issue by aCLr** [hexdigest/gowrap#41]
Greetings!
We use gowrap and golines in out project. As you can see [here](https://github.com/segmentio/golines/blob/master/shortener.go#L608) golines checks a few top lines of each file to check if it generated, but gowrap places comments after imports block
<details>
  <summary>Screenshot</summary>
![image](https://user-images.githubusercontent.com/6426720/136575496-b641600a-e7e2-4922-aa9d-db17b5bc81f9.png)

</details>

Could you fix it and place comments on the top?

**Comment by breml** [comment]
Duplicate of #20

**Comment by hexdigest** [comment]
Hi @aCLr,

This problem is fixed in [v1.2.7](https://github.com/hexdigest/gowrap/releases/tag/v1.2.7)
