### ISSUE TITLE
Add Masterminds/sprig template functions

### ISSUE THREAD

**Issue by breml** [hexdigest/gowrap#44]
I had a situation, where it would have been helpful, if `gowrap` would allow some basic artithmetic in the templates. Go templates by default only have a very limited set of functions available.

https://github.com/Masterminds/sprig provides a rich set of useful [functions for Go templates](http://masterminds.github.io/sprig/) and therefore I propose to add this package to `gowrap` and make these functions available.

**Comment by Fryuni** [comment]
This would be awesome
