### ISSUE TITLE
Reason for errUnexportableType error

### ISSUE THREAD

**Issue by sjames-iberis** [hexdigest/gowrap#6]
I am curious to know why the use of an unexported type should abort decorator generation (line 138 of printer.go).

I want to generate decorators for an interface that is only used in the context of the package in which it is defined, but this error blocks me from doing that.

If I comment out the check, everything is generated as I need.

**Comment by hexdigest** [comment]
@sjames-iberis unexported type should stop the generation only in case when destination .go file is not in the package of the interface. If the destination package is the same as the source package everything should work fine.

**Comment by sjames-iberis** [comment]
Sorry, I don't understand. I have the trivial source service.go:
```
package egp
type Service interface {
	Method(request reportRequest) 
}

type reportRequest struct {
	field string 
}
```

I invoke gowrap with:
```
 gowrap gen -d egp  -i Service -t custtmp -o egp/out.go
```
and get the result:
```
failed to parse interface declaration: reportRequest: unexportable type
```
The destination .go file is in the same package as the interface, but I still see the error.

**Comment by hexdigest** [comment]
@sjames-iberis Thanks, fixed! Can you please check that everything works fine for you?

**Comment by sjames-iberis** [comment]
Confirming that this issue has been fixed. Thanks.
