### ISSUE TITLE
method.Declaration does not add package names in argument types and return types

### ISSUE THREAD

**Issue by zshehov** [hexdigest/gowrap#62]
The
```    func (_d {{$decorator}}) {{$method.Declaration}} { ```
line generates 

```func (_d wrapped) Method(ctx context.Context, paramName ParamType) (returnName ReturnType)```
instead of the expected
```func (_d wrapped) Method(ctx context.Context, paramName wrappedtype.ParamType) (returnName wrappedtype.ReturnType)```

This change in behaviour has happened between release 1.2.7 and 1.3.0

**Comment by rangzen** [comment]
Hello @hexdigest, any news on this one? We force 1.2.7 right now.

**Comment by hexdigest** [comment]
@zshehov @rangzen 

Hey folks, I reverted generics feature since it introduced some major issues. You can try latest [v1.3.1 release](https://github.com/hexdigest/gowrap/releases/tag/v1.3.1)

cc @NoGambiNoBugs

**Comment by NoGambiNoBugs** [comment]
@hexdigest I will test this case, is true that the generics feature change some crucial code in `params.go` file, but I think that is a simple fix.

**Comment by NoGambiNoBugs** [comment]
@hexdigest I tested this example, but for me it works well, here is the examples using the version of PR https://github.com/hexdigest/gowrap/pull/68.

- Interface Declaration: https://github.com/NoGambiNoBugs/gowrap-generics-examples/blob/master/port/issues_port.go
- Code Generated: https://github.com/NoGambiNoBugs/gowrap-generics-examples/blob/master/decorators/issue_62.go

**Comment by hexdigest** [comment]
@zshehov 

Please try latest [v1.3.2 release](https://github.com/hexdigest/gowrap/releases/tag/v1.3.2) with generics functionality.
