### ISSUE TITLE
Appear in Nixpkgs

### ISSUE THREAD

**Issue by Dafaque** [hexdigest/gowrap#69]
I'm building a universal development environment for a team using Nix, only gowrap is missing for a complete spec. Could you consider adding your package to the Nixpkgs repository?
Here is docs
https://nixos.wiki/wiki/Nixpkgs/Create_and_debug_packages

And here is oapi-codegen tool example
https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/tools/networking/oapi-codegen/default.nix

**Comment by hexdigest** [comment]
Hey @Dafaque,

I don't have time for that.
