### ISSUE TITLE
Access to Package Name in Body Template

### ISSUE THREAD

**Issue by sjames-iberis** [hexdigest/gowrap#7]
We need access to the interface’s package name in a template.  
We can see this is available when the header template is executed, but don’t think it is available to body templates.  
Could this be made available in the map?

Also, is there any way to customise the header template?

**Comment by hexdigest** [comment]
@sjames-iberis I didn't want to customize the header because giving two templates as an input to gowrap is kinda too much and may confuse people. Why do you need it?

**Comment by sjames-iberis** [comment]
Customising header template is not a big issue. I only raised it because it would have provided a way to use the package name in the body (for example, by declaring a constant that the body could reference). 

We need the package name in the body because we have a number packages which have an interface with the same name and method signature. 

The package name is needed to identify which variant of the method is being invoked, for example in logging.

**Comment by hexdigest** [comment]
@sjames-iberis Thanks for the explanation, I got your point. Exposing source package metadata and destination package metadata to the body template is not a problem and can be done easily, however I was thinking about passing any kind of vars to the body template from the command line in the form of key/value pairs. So that way, the decorator struct name/constructor name can be passed from the command line too. I think it will be a more generic solution. Does it make sence to you?

**Comment by sjames-iberis** [comment]
Although I would still prefer it if all properties of the source interface were automatically available to the template, being able to define key/value pairs from the command line is definitely a useful feature, and we could leverage it make the package name available.  

Thanks!

**Comment by hexdigest** [comment]
@sjames-iberis please check new -v flags for setting .Vars from the command line.

I also changed all templates in the repo so now they aware of .Vars.DecoratorName which can be set via -v

This is an example from the templates_tests/interface_with_log.go:

```
gowrap gen -d . -i TestInterface -t ../templates/log -o interface_with_log.go -v DecoratorName=TestInterfaceWithLogger
```
You can pass multiple vars to the templates by using -v flag multiple times.

Please close the issue if this approach works for you.

**Comment by sjames-iberis** [comment]
Confirmed that -v option can be used to define package name.
