### ISSUE TITLE
Access to Documentation Comments

### ISSUE THREAD

**Issue by sjames-iberis** [hexdigest/gowrap#8]
We would like to be able to make interface and method ‘documentation’ comments available to templates.  

For example, we would like to use a method comment to provide hints to a logging decorator about what and how to log specific params and results (avoiding monolithic log output, hiding sensitive data etc)

The documentary comments are readily available in the ast and so could be copied to the template input. 

I’m happy to prototype this and raise a pull request, but would welcome your opinion on whether this would be a useful feature.

**Comment by hexdigest** [comment]
@sjames-iberis I was thinking about it and it totally makes sence. Feel free to raise a PR.

**Comment by Varriount** [comment]
Was this ever completed?

**Comment by hexdigest** [comment]
@sjames-iberis @Varriount 
Please take a look at https://github.com/hexdigest/gowrap/pull/36
