### ISSUE TITLE
Feature Request: allow passing in a span decorator function in the constructor of the opentracing template

### ISSUE THREAD

**Issue by trusch** [hexdigest/gowrap#9]
I as a developer want to be able to pass in a function which will populate the tracing span with domain specific logs / baggage items. This would enable easier to read traces + allow more fine grained control of what NOT to trace (i.e. the context object for example). This would also be needed to prevent sensitive data like passwords to be logged.

**Comment by hexdigest** [comment]
@trusch I added optional spanDecorator parameter to the constructor, please check.
